version: '3'
services:
  # ChromaDB service
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Your FastAPI service
  fastapi:                              
    image: medinsightregistry.azurecr.io/nsharandroidnstudiomedinsightaudioapi:latest 
    container_name: fastapi_app
    ports:
      - "80:80"
    depends_on:
      - chromadb
      - mongo
    environment:
      MONGO_HOST: mongo  # Use service name for MongoDB connection

volumes:
  chroma_data:
  mongo_data:
